### PR TITLE
Make suspending methods use 'await' prefix

### LINKED ISSUE #45: expectNoEvents() not working?
I'm trying to test a Room Flow like the following:

```kotlin
 runBlocking {
    underTest.saveStuff(listOf(FIRST, SECOND)) // suspending DAO INSERT call

    roomExecutor.drain() // androidx.arch.core:core-testing's CountingTaskExecutorRule::drainTasks shortcut
    yield()

    underTest.observeStuff().test {
        assertThat(expectItem()).hasSize(2)
    }
}
```

Now when I execute this test, all is ok and green. But, to my surprise, if I verify like this

```kotlin
    underTest.observeStuff().test {
        expectNoEvents()
    }
```

the test won't fail either! I can even chain this and the test keeps green:

```kotlin
    underTest.observeStuff().test {
        expectNoEvents()
        assertThat(expectItem()).hasSize(2)
    }
```

How can it be that there are apparently no events verified, but if we look more closer, there are events? Can one rely at all on `expectNoEvents()`?

### PR DESCRIPTION
**Pull request by JakeWharton**
This is in contrast to 'cancel' and 'expect' methods which do not.

Closes #45.

### CODE REVIEW

File: src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt [hunk 1]
```diff
@@ -275,15 +287,13 @@ private class ChannelBasedFlowTurbine<T>(
 
   override fun expectMostRecentItem(): T {
     var recentItem: Event.Item<T>? = null
-    var event: Event<T>? = events.tryReceive().getOrNull()
-    while (event != null) {
-      when (event) {
+    while (true) {
+      when (val event = events.tryReceive().getOrNull()) {
+        null -> break
```
Comment (Egorand) [inline src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt:292]: Nice

**Review by Egorand — APPROVED** [review]
