### PR TITLE
Fix improper exception segregation

### LINKED ISSUE #208: TimeoutCancellationException is not catched
Snippet to replicate the issue
```
@Test
fun shouldTimeOut() = runTest {
    suspend fun number(): Int {
        delay(2000)
        return 1
    }

    flow {
        emit(0)
        withTimeout(1000) {
            emit(number())
        }
    }.test(3.seconds) {
        assertEquals(0, awaitItem())
        assertTrue(awaitError() is TimeoutCancellationException)
    }
}
```
Expected : the test passes.
Actual : the test fails with `No value produced in 3s`

(Original slack message for a bit more context : https://kotlinlang.slack.com/archives/C5HT9AL7Q/p1680097861931639)

### PR DESCRIPTION
**Pull request by jingibus**
Fixes #208

### CODE REVIEW

File: src/commonTest/kotlin/app/cash/turbine/FlowTest.kt [hunk 1]
```diff
@@ -727,4 +733,25 @@ class FlowTest {
...
+      withTimeout(500) {
+        delay(2000)
+      }
+    }.test {
+      assertTrue(awaitError() is TimeoutCancellationException)
+    }
+  }
+
+  @Test
+  fun cancellationsAreCaptured() = runTest {
```
Comment (jingibus) [inline src/commonTest/kotlin/app/cash/turbine/FlowTest.kt:749]: Not sure how I feel about this behavior, but... gut feeling is that this is less wrong to me than the alternatives.

**Review by JakeWharton — APPROVED** [review]
