### PR TITLE
Throw unconsumed events if the scope is cancelled

### LINKED ISSUE #247: `test` and `testIn` do not behave consistently
I've noticed that if a `Flow` is canceled "externally" (e.g. a `StateFlow` that is canceled only when the `CoroutineScope` it was launched in is canceled) then `test` and `testIn` do not behave the same.

While `test` reports all unconsumed events and fails the test, `testIn` does not and passes the test.

```kt
private val flow = flow {
  emit(1)
  emit(2)
  awaitCancellation()
}

// Throws
//   app.cash.turbine.TurbineAssertionError: Unconsumed events found:
//    - Item(2)
@Test
fun test() = runTest {
  flow.test {
    assertEquals(1, awaitItem())
  }
}

// Passes
@Test
fun testIn() = runTest {
  turbineScope {
    val turbine = flow.testIn(backgroundScope)
    assertEquals(1, turbine.awaitItem())
  }
}
```

This is not necessarily caused by the `backgroundScope` as it can be replicated with a custom `CoroutineScope()` + `scope.cancel()` or even when canceling the `Job` the turbine was launched in.

I've figured out this behavior is caused by not handling `CancellationException` as a special case. From the docs of `CancellationException`: "_It indicates normal cancellation of a coroutine_".

### PR DESCRIPTION
**Pull request by Antimonit**
This potentially fixes https://github.com/cashapp/turbine/issues/247.

### CODE REVIEW

File: src/commonMain/kotlin/app/cash/turbine/Turbine.kt [hunk 1]
```diff
@@ -211,6 +211,7 @@ internal class ChannelTurbine<T>(
     var cause: Throwable? = null
     while (true) {
       val event = channel.takeEventUnsafe() ?: break
+      if (event is Event.Error && event.throwable is CancellationException) break
```
Comment (jingibus) [inline src/commonMain/kotlin/app/cash/turbine/Turbine.kt:214]: I really like the idea of just eating these at the source. I had dealt with `CancellationException` in an ad-hoc manner when implementing `turbineScope`, and this is much cleaner

File: src/commonMain/kotlin/app/cash/turbine/flow.kt [hunk 2]
```diff
@@ -195,7 +195,8 @@ private fun <T> testInInternal(flow: Flow<T>, timeout: Duration?, scope: Corouti
     if (debug) println("Scope ending ${exception ?: ""}")
 
     // Only validate events were consumed if the scope is exiting normally.
-    if (exception == null) {
+    // CancellationException also indicates _normal_ cancellation of a coroutine.
+    if (exception == null || exception is CancellationException) {
```
Comment (jingibus) [inline src/commonMain/kotlin/app/cash/turbine/flow.kt:199]: I think we can actually get rid of this whole `invokeOnCompletion`; `turbineScope` now has the code to run this validation, so we don't need it here. I'm kinda surprised it works, actually

Does not need to be changed before merge, I'll clean it up in a followup PR

**Review by jingibus — APPROVED** [review]
Thanks for this work. It points at some more cleanup that needs to be done related to the new `turbineScope`, but I'll deal with that in a followup PR!
