### PR TITLE
Include real timeout exception in friendly timeout exception

### LINKED ISSUE #189: Assertion stacktrace is not reported on `awaitItem()` timeout
### **Problem:**

Consider this test where `awaitItem()` fails due to a timeout:

```kotlin
class FlowTest {

  @Test fun fail() = runTest {
    flow {
      emit(1)
      emitAll(neverFlow()) // Avoid emitting complete
    }.test(timeout = 10.milliseconds, name = "never flow") { // L:59
      assertEquals(awaitItem(), 1)
      awaitItem() // L:61 - timeouts here
    }
  }
```

The stacktrace produced:

```java
No value produced for never flow in 10ms
java.lang.AssertionError: No value produced for never flow in 10ms
	at app.cash.turbine.ChannelKt.awaitEvent(channel.kt:92)
	at app.cash.turbine.ChannelKt$awaitEvent$1.invokeSuspend(channel.kt)
	(Coroutine boundary)
	at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:57)
	at app.cash.turbine.FlowTest$fail$1.invokeSuspend(FlowTest.kt:59)
    ....
```

Note how failure trace points to `test` call on `FlowTest.kt:59`, but expected `FlowTest.kt:61`. With that, it's not obvious which of the `awaitItem()` calls timed out.

### **Cause:**

Looking at `awaitEvent()` implementation, it looks like we are rethrowing a timeout exception by creating a fresh `AssertionError` with new custom message without preserving the stacktrace:

```kotlin
/**
 * Assert that an event was received and return it.
 * This function will suspend if no events have been received.
 *
 * This function will always return a terminal event on a closed [ReceiveChannel].
 */
public suspend fun <T> ReceiveChannel<T>.awaitEvent(name: String? = null): Event<T> {
  val timeout = contextTimeout()
  return try {
    withAppropriateTimeout(timeout) {
      val item = receive()
      Event.Item(item)
    }
  } catch (e: TimeoutCancellationException) {
    throw AssertionError("No ${"value produced".qualifiedBy(name)} in $timeout")
  } catch (e: TurbineTimeoutCancellationException) {
    throw AssertionError("No ${"value produced".qualifiedBy(name)} in $timeout")
  } catch (e: CancellationException) {
    throw e
  } catch (e: ClosedReceiveChannelException) {
    Event.Complete
  } catch (e: Throwable) {
    Event.Error(e)
  }
}
```

### **(Incomplete) solution:**

If we rethrow original timeout exceptions directly...:
```kotlin
  } catch (e: TimeoutCancellationException) {
    throw e
  } catch (e: TurbineTimeoutCancellationException) {
    throw e
```

We get the stacktrace we want:
```kotlin
Timed out waiting for 10ms
app.cash.turbine.TurbineTimeoutCancellationException: Timed out waiting for 10ms
	at app//app.cash.turbine.ChannelKt$withWallclockTimeout$2$1$2.invokeSuspend(channel.kt:133)
	(Coroutine boundary)
	at app.cash.turbine.ChannelKt$withWallclockTimeout$2.invokeSuspend(channel.kt:279)
	at app.cash.turbine.ChannelKt.awaitEvent(channel.kt:85)
	at app.cash.turbine.ChannelKt.awaitItem(channel.kt:200)
	at app.cash.turbine.ChannelTurbine$awaitItem$2.invokeSuspend(Turbine.kt:191)
	at app.cash.turbine.FlowTest$fail$1$2.invokeSuspend(FlowTest.kt:61) // <--- YAY
```

This however now causes the test not to fail due to an assertion but to fail due to an unexpected error which we probably don't want.

Relevant discussion: https://androidstudygroup.slack.com/archives/C03NYGB45/p1670615690205989.

### PR DESCRIPTION
**Pull request by JakeWharton**
Otherwise the actual call site is lost.

Closes #189

### CODE REVIEW

File: src/commonMain/kotlin/app/cash/turbine/channel.kt [hunk 1]
```diff
@@ -87,9 +87,9 @@ public suspend fun <T> ReceiveChannel<T>.awaitEvent(name: String? = null): Event
       Event.Item(item)
     }
   } catch (e: TimeoutCancellationException) {
-    throw AssertionError("No ${"value produced".qualifiedBy(name)} in $timeout")
+    throw TurbineAssertionError("No ${"value produced".qualifiedBy(name)} in $timeout", e)
   } catch (e: TurbineTimeoutCancellationException) {
-    throw AssertionError("No ${"value produced".qualifiedBy(name)} in $timeout")
+    throw TurbineAssertionError("No ${"value produced".qualifiedBy(name)} in $timeout", e)
```
Comment (jingibus) [inline src/commonMain/kotlin/app/cash/turbine/channel.kt:92]: Ahh, because we `override val cause` in `TurbineAssertionError` 🤔

**Review by jingibus — APPROVED** [review]

**Review by kirillzh — APPROVED** [review]

File: src/commonMain/kotlin/app/cash/turbine/channel.kt (hunk 1 above)
Comment (JakeWharton) [reply src/commonMain/kotlin/app/cash/turbine/channel.kt:92]: Built in one is coming now that Java 8 is the minimum: https://youtrack.jetbrains.com/issue/KT-40728
